-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.softcartdimdate
(
    dateid integer NOT NULL,
    fulldate date NOT NULL,
    year integer NOT NULL,
    quarter integer NOT NULL,
    month integer NOT NULL,
    monthname character varying(20) COLLATE pg_catalog."default" NOT NULL,
    day integer NOT NULL,
    weekday integer NOT NULL,
    weekdayname character varying(20) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT softcartdimdate_pkey PRIMARY KEY (dateid)
);

CREATE TABLE IF NOT EXISTS public."softcartDimCategory"
(
    categoryid integer NOT NULL,
    categoryname character varying(100) NOT NULL,
    description text,
    PRIMARY KEY (categoryid)
);

CREATE TABLE IF NOT EXISTS public."softcartDimItem"
(
    itemid integer NOT NULL,
    itemname character varying(150) NOT NULL,
    categoryid integer NOT NULL,
    sku character varying(50) NOT NULL,
    brand character varying(100) NOT NULL,
    description text NOT NULL,
    price numeric(10, 2) NOT NULL,
    PRIMARY KEY (itemid)
);

CREATE TABLE IF NOT EXISTS public."softcartDimCountry"
(
    countryid integer NOT NULL,
    countryname character varying(100) NOT NULL,
    countrycode character(3) NOT NULL,
    region character varying(100) NOT NULL,
    subregion character varying(100) NOT NULL,
    PRIMARY KEY (countryid)
);

CREATE TABLE IF NOT EXISTS public."softcartFactSales"
(
    "orderID" integer NOT NULL,
    "itemID" integer NOT NULL,
    "categoryID" integer NOT NULL,
    price numeric(10, 2) NOT NULL,
    "countryID" integer NOT NULL,
    dateid integer NOT NULL,
    PRIMARY KEY ("orderID")
);

ALTER TABLE IF EXISTS public."softcartFactSales"
    ADD FOREIGN KEY ("itemID")
    REFERENCES public."softcartDimItem" (itemid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."softcartFactSales"
    ADD FOREIGN KEY ("categoryID")
    REFERENCES public."softcartDimCategory" (categoryid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."softcartFactSales"
    ADD FOREIGN KEY ("countryID")
    REFERENCES public."softcartDimCountry" (countryid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."softcartFactSales"
    ADD FOREIGN KEY (dateid)
    REFERENCES public.softcartdimdate (dateid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;